/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AdicionarLivroController;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Reinan
 */
public class AdicionarLivro extends javax.swing.JFrame {

    private final AdicionarLivroController controller;
    /**
     * Creates new form AdicionarLivro
     */
    public AdicionarLivro() {
        initComponents();
        controller = new AdicionarLivroController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAgenda = new javax.swing.JLabel();
        LabelId = new javax.swing.JLabel();
        LabelCliente = new javax.swing.JLabel();
        LabelServico = new javax.swing.JLabel();
        LabelValor = new javax.swing.JLabel();
        LabelData = new javax.swing.JLabel();
        LabelHora = new javax.swing.JLabel();
        paginaTxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        ButtonAgendar = new javax.swing.JButton();
        LabelHora1 = new javax.swing.JLabel();
        autorTxt = new javax.swing.JTextField();
        JComboBoxPretoBranco = new javax.swing.JComboBox<>();
        JComboBoxLerTrasFrente = new javax.swing.JComboBox<>();
        generoTxt = new javax.swing.JTextField();
        tituloTxt = new javax.swing.JTextField();
        valorTxt = new javax.swing.JTextField();
        TextId = new javax.swing.JTextField();
        LabelId1 = new javax.swing.JLabel();
        LabelAgendaPainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelAgenda.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        LabelAgenda.setForeground(new java.awt.Color(255, 255, 255));
        LabelAgenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAgenda.setText("Adicionar Livro ao Acervo");
        getContentPane().add(LabelAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 460, 60));

        LabelId.setForeground(new java.awt.Color(255, 255, 255));
        LabelId.setText("Titulo");
        getContentPane().add(LabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        LabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        LabelCliente.setText("Genero");
        getContentPane().add(LabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        LabelServico.setForeground(new java.awt.Color(255, 255, 255));
        LabelServico.setText("Autor");
        getContentPane().add(LabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        LabelValor.setForeground(new java.awt.Color(255, 255, 255));
        LabelValor.setText("Valor R$");
        getContentPane().add(LabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        LabelData.setForeground(new java.awt.Color(255, 255, 255));
        LabelData.setText("Paginas");
        getContentPane().add(LabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, -1));

        LabelHora.setForeground(new java.awt.Color(255, 255, 255));
        LabelHora.setText("Preto e Branco");
        getContentPane().add(LabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        paginaTxt.setText("0");
        paginaTxt.setToolTipText("");
        paginaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginaTxtActionPerformed(evt);
            }
        });
        getContentPane().add(paginaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 280, 40));

        jButton3.setBackground(new java.awt.Color(51, 255, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 40));

        ButtonAgendar.setBackground(new java.awt.Color(60, 233, 106));
        ButtonAgendar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ButtonAgendar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAgendar.setText("Agendar");
        ButtonAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 460, 40));

        LabelHora1.setForeground(new java.awt.Color(255, 255, 255));
        LabelHora1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelHora1.setText("Leitura da esqueda pra direita");
        LabelHora1.setToolTipText("");
        getContentPane().add(LabelHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, 30));

        autorTxt.setToolTipText("<String>");
        autorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorTxtActionPerformed(evt);
            }
        });
        getContentPane().add(autorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 280, 40));

        JComboBoxPretoBranco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim ", "Nao", " " }));
        JComboBoxPretoBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxPretoBrancoActionPerformed(evt);
            }
        });
        getContentPane().add(JComboBoxPretoBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 280, 40));

        JComboBoxLerTrasFrente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", " ", "Nao" }));
        JComboBoxLerTrasFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxLerTrasFrenteActionPerformed(evt);
            }
        });
        getContentPane().add(JComboBoxLerTrasFrente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 280, 40));

        generoTxt.setText("0");
        generoTxt.setToolTipText("");
        generoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(generoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 280, 40));

        tituloTxt.setText("0");
        tituloTxt.setToolTipText("");
        tituloTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloTxtActionPerformed(evt);
            }
        });
        getContentPane().add(tituloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 280, 40));

        valorTxt.setText("0");
        valorTxt.setToolTipText("");
        valorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTxtActionPerformed(evt);
            }
        });
        getContentPane().add(valorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 280, 40));

        TextId.setEditable(false);
        TextId.setText("0");
        TextId.setToolTipText("");
        TextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdActionPerformed(evt);
            }
        });
        getContentPane().add(TextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 280, 40));

        LabelId1.setForeground(new java.awt.Color(255, 255, 255));
        LabelId1.setText("Id");
        getContentPane().add(LabelId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        LabelAgendaPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagem/PainelFundo.png"))); // NOI18N
        getContentPane().add(LabelAgendaPainelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1150, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagem/Biblioteca-fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paginaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paginaTxtActionPerformed

    private void ButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgendarActionPerformed
        this.controller.inserirManga();
    }//GEN-LAST:event_ButtonAgendarActionPerformed

    private void autorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorTxtActionPerformed

    private void JComboBoxPretoBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxPretoBrancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxPretoBrancoActionPerformed

    private void JComboBoxLerTrasFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxLerTrasFrenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxLerTrasFrenteActionPerformed

    private void generoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoTxtActionPerformed

    private void tituloTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloTxtActionPerformed

    private void valorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTxtActionPerformed

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        controller.voltarMenu();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgendar;
    private javax.swing.JComboBox<String> JComboBoxLerTrasFrente;
    private javax.swing.JComboBox<String> JComboBoxPretoBranco;
    private javax.swing.JLabel LabelAgenda;
    private javax.swing.JLabel LabelAgendaPainelFundo;
    private javax.swing.JLabel LabelCliente;
    private javax.swing.JLabel LabelData;
    private javax.swing.JLabel LabelHora;
    private javax.swing.JLabel LabelHora1;
    private javax.swing.JLabel LabelId;
    private javax.swing.JLabel LabelId1;
    private javax.swing.JLabel LabelServico;
    private javax.swing.JLabel LabelValor;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextField autorTxt;
    private javax.swing.JTextField generoTxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField paginaTxt;
    private javax.swing.JTextField tituloTxt;
    private javax.swing.JTextField valorTxt;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
        
    }
    
    public JComboBox<String> getJComboBoxLerTrasFrente() {
        return JComboBoxLerTrasFrente;
    }

    public void setJComboBoxLerTrasFrente(JComboBox<String> JComboBoxLerTrasFrente) {
        this.JComboBoxLerTrasFrente = JComboBoxLerTrasFrente;
    }

    public JComboBox<String> getJComboBoxPretoBranco() {
        return JComboBoxPretoBranco;
    }

    public void setJComboBoxPretoBranco(JComboBox<String> JComboBoxPretoBranco) {
        this.JComboBoxPretoBranco = JComboBoxPretoBranco;
    }

    public JTextField getTextId() {
        return TextId;
    }

    public void setTextId(JTextField TextId) {
        this.TextId = TextId;
    }

    public JTextField getAutorTxt() {
        return autorTxt;
    }

    public void setAutorTxt(JTextField autorTxt) {
        this.autorTxt = autorTxt;
    }

    public JTextField getGeneroTxt() {
        return generoTxt;
    }

    public void setGeneroTxt(JTextField generoTxt) {
        this.generoTxt = generoTxt;
    }

    public JTextField getPaginaTxt() {
        return paginaTxt;
    }

    public void setPaginaTxt(JTextField paginaTxt) {
        this.paginaTxt = paginaTxt;
    }

    public JTextField getTituloTxt() {
        return tituloTxt;
    }

    public void setTituloTxt(JTextField tituloTxt) {
        this.tituloTxt = tituloTxt;
    }

    public JTextField getValorTxt() {
        return valorTxt;
    }

    public void setValorTxt(JTextField valorTxt) {
        this.valorTxt = valorTxt;
    }

   
    
    

   

  

    

}



